services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/tmp              # Air 編譯 cache，避免被本機覆蓋
    ports:
      - "8080:8080"
    depends_on:
      - move

  move:
    image: mysten/sui-tools:devnet
    working_dir: /move
    volumes:
      - ./move:/move
    tty: true
